sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: ***
    port: ***
    database: sky_take_out
    username: ***
    password: ***

  alioss:
    endpoint: oss-cn-chengdu.aliyuncs.com
    access-key-id: ***
    access-key-secret: ***
    bucket-name: baby-shark

  redis:
    host: ***
    port: ***
    password: ***
    database: ***

  wechat:
    appid: ***
    secret: ***
