sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 8.137.123.85
    port: 3306
    database: sky_take_out
    username: root
    password: 472020

  alioss:
    endpoint: oss-cn-chengdu.aliyuncs.com
    access-key-id: LTAI5tN33K76pDW6rRntiswy
    access-key-secret: UZDzq4IW9OzCFkmvKeMXDGdZBnP34j
    bucket-name: baby-shark